### ISSUE TITLE
Release 1

### ISSUE THREAD

**Issue by theaspect** [arxangel008/TRPO#1]
1. Исправь кодировку на юникод
1. Избавься от пустых файлов и закомментированных кусков кода
1. Не понимаю где заполняется база
1. Перепиши на h2db http://www.h2database.com/html/cheatSheet.html
1. Коннекты и prepared statement должны быть закрыты после использования иначе ресурсы будут утекать
1. Как твое приложение обработает jdow read a.b.c....x.y.z? В требованиях ничего не сказано про ограниченность ресурсов
3. addOption(makeOptionWithArgument можно записать как .addOption("c", true, "country code") https://commons.apache.org/proper/commons-cli/apidocs/index.html
4. зачем Role сделан дочерним энумом? Вынеси в отдельный класс
4. Глядя на переменные you и first какой можно сделать вывод о значении этих переменных
4. Имя не соответствует стандарту PreparedStatement PS http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-135099.html#367
5. зачем нужна глобальная перменная resID = resource_id;?

**Comment by theaspect** [comment]
Для версии v1.1 https://github.com/arxangel008/TRPO/compare/v1.0...v1.1

Выполнен только пункт 6

**Comment by theaspect** [comment]
1. исправь jdbс коннекшен  чтобы база создавалась в текущей директории
```
-        return DriverManager.getConnection("jdbc:h2:~/test", "sa", "");
+        return DriverManager.getConnection("jdbc:h2:./test", "sa", "");
```
2. пункт 3 из предыдущего все еще справедлив: база данных не заполняется при запуске ошибки
```
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Table "AUTH" not found; SQL statement:
SELECT * FROM Auth WHERE login=? [42102-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5293)
	at org.h2.command.Parser.readTableFilter(Parser.java:1234)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1873)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1982)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1867)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1688)
	at org.h2.command.Parser.parseSelect(Parser.java:1676)
	at org.h2.command.Parser.parsePrepared(Parser.java:432)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at com.company.Main.main(Main.java:72)
TESTING FAIL [-login jdoe -pass sup3rpaZZ -role read -res a -ds XXX -de XXX -vol XXX] 1 != 5
```
